# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbf353c5b038703caa9970f4a5e4e4f64c04cf4b1427fdd6600b81e9ace2819736255b6615d75ae07334646b6d6349b81708455bbd944c82079d29cd22113ea

test:
  secret_key_base: c6e506d9c832db75758be74602ca8e499bc87686c8e23110525b503ff71d4def57d1cf1e594e1961613fd426172c92cfed9b727a14566269c36909a54fe8b271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
